{% set name = "hesperos" %}
{% set version = "0.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/hesperos-{{ version }}.tar.gz
  sha256: 3434d080f68dd1ab678de9a0787365c58ee913840f66de3ed0f63fb6bc19ab8a

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools-scm
  run:
    - imageio-ffmpeg
    - napari <0.4.15
    - napari-plugin-engine
    - numpy
    - pandas
    - python >={{ python_min }}
    - qtpy
    - scikit-image
    - scikit-learn
    - scipy
    - simpleitk
    - tifffile

test:
  imports:
    - hesperos
  commands:
    - pip list
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/chgodard/hesperos
  summary: A plugin to manually or semi-automatically segment medical data and correct previous segmentation data.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - goanpeca
    - jaimergp
